skip_commits:
 files:
   - docs/*
   - .travis.yml
skip_branch_with_pr: true
max_jobs: 6
image: Visual Studio 2015
platform: x64
configuration: Debug
init:
  - git config --global core.autocrlf input
clone_depth: 1
matrix:
  fast_finish: true
install:
  # conda 4.5.11 seems to expect that this directory exists already
  - mkdir C:\Users\appveyor\.conda
  - call C:\Miniconda37-x64\Scripts\activate.bat
  # The safety checks are simply intended to ensure that there is enough disk space
  # and the user has the necessary permissions to make environment changes. In a CI
  # environment these are not necessary and slow things down noticeably on Windows.
  - >
    conda config
    --set always_yes yes
    --set changeps1 no
    --set auto_update_conda no
    --set safety_checks disabled
  - conda create -n foam_ct_phantom -c conda-forge python=3.7 numpy scipy tqdm h5py psutil numba sortedcollections openmp pathlib2 setuptools scikit-build
  - conda activate foam_ct_phantom
  - conda info -a
  - conda list --explicit
  - python setup.py install
# Not a .NET project, we build in the install step instead
build: false
test_script:
  - cd examples
  - python -c "import os; os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'; import foam_ct_phantom"